### ISSUE TITLE
Update RFC README

### ISSUE THREAD

**Issue by heather999** [heather999/RequestForComments#10]
As discussed in RFC #9
update the README to include scope, examples and an outline of this agreed RFC checklist.

**Comment by JoanneBogart** [comment]
I suggest we change this sentence

> The individual submitting the request is not expected to take part in the implementation of the idea presented.

because someone submitting a request could take it to mean they're not supposed to take part in the implementation, which I assume is not what we want.   How about something like
> The individual submitting the request is not obligated  (but is welcome) to take part in the implementation of the idea presented

?

**Comment by heather999** [comment]
Yes - sounds good to me!

**Comment by heather999** [comment]
Done and merged via #11
