### ISSUE TITLE
Draft RFC announcement

### ISSUE THREAD

**Issue by heather999** [heather999/RequestForComments#12]
As part of implementing RFC #9
Draft here: https://docs.google.com/document/d/1qk8AYaWKK7iPRRwjDJhr5dzdRaT7_vYixSnS1rVMGkY/edit?usp=sharing  Pinging @JoanneBogart @johannct @yymao @eacharles

**Comment by JoanneBogart** [comment]
Other than one little suggestion I made, this looks fine to me.  
Especially since it has a link to the README, we should finish off https://github.com/LSSTDESC/RequestForComments/issues/10 before sending the announcement.

**Comment by heather999** [comment]
Address Joanne's and Yao's suggestions - thank you!  I'll post this to the compconveners channel to see if anyone else would like to chime in.  Hoping to get this out today or tomorrow morning pending any further discussion.

**Comment by heather999** [comment]
After sending one last reminder to #desc-compconveners, we're ready to make this announcement.
