### ISSUE TITLE
[RFC] Enabling Discussions in github for desc-help and/or RFC

### ISSUE THREAD

**Issue by johannct** [heather999/RequestForComments#3]
**Summary**

*Insert Descriptive Summary*
Discussions is an option in a GH repo settings tab, that allows to capture interactions on topics without opening an issue

**Description**

*Insert brief background on why this proposal is being made. Ensure that you clearly state your actual, actionable, proposal.*
See here : https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
The point may be that this would make usage of issues cleaner and more restricted. Do we have examples of usages within project or DESC?

**Planned End Date**

*at least 72 hours in the future for ordinary issues or 1 week ahead for major issues.*
undefined.

**Comment by heather999** [comment]
@johannct I want to make sure I understand this suggestion - this repo has an issue template for "RFC" to open a discussion as a GitHub Issue, do you also want to make the GitHub "Discussions" feature available? My concern is that it will cause confusion over where to start a topic.

**Comment by johannct** [comment]
I am not sure..... This issue was raised so that the possible usage of the discussion tab in github be investigated if deemed useful. But I confess that I did not find time to investigate. My worry with discussions within issues is the lack of threading, but it might just be a necessary evil.

**Comment by heather999** [comment]
I think what I'm suggesting is that we start with just GH issues, but we can revisit this.  I'd consider it a triumph if we find this repo actually gets used :)  Our many places for communicating is overwhelming already and difficult to track - but what I like about the issues is that this is a more structured place to capture topics that may need to be available for search and can easily be pointed to for future reference.
 
Now I will mention, GH provides a way to [convert issues into discussions(using labels)](https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions-in-your-repository#converting-issues-based-on-labels) and seems to be working to offer a mechanism to convert a discussion into an issue: https://github.com/github/feedback/discussions/2861
