### ISSUE TITLE
[RFC] Define a simple checklist outlining the RFC process

### ISSUE THREAD

**Issue by heather999** [heather999/RequestForComments#9]
**Summary**

As discussed at the [CO meeting this week](https://docs.google.com/document/d/11Qb-RNSDuyOwQySDI2FgNeiFuaCFKPPmEIYeGyq7T3I/edit#bookmark=id.prwgs9l6oksh), we would like to define a very light process as we prepare to announce this to the collaboration.

Comment period closes when we reach consensus or after one week on Thursday, Sept 30, 2021

**Description**

Just throwing this together, please offer comments and hopefully we can come to some consensus.

Some very simple steps for responding to an RFC:
* Once the RFC issue is created, a notification will be posted to the #desc-co Slack channel
* All are welcome to respond during the comment period which is nominally one week
* When a preliminary decision has been made, it will be outlined in the RFC issue and a final opportunity will be provided for people to comment.
* After the comment period has closed and a decision is made, it will be summarized in the RFC issue.
* If the RFC results in some decision or action, the issue will be labelled "adopted"
* If the RFC cannot be accepted, the issue will be labelled "withdrawn"
* If an adopted RFC requires action for implementation, a [new Project will created in this repo](https://github.com/LSSTDESC/RequestForComments/projects)
   * Issues will be opened to address all tasks necessary.
   * Once all the issues are closed, the RFC will be labelled as "implemented"

**Comment by heather999** [comment]
From Johann on Slack:  

> LGTM. We should announce to #desc-announce about the setup of this DESC RFC protoype though. #fdesc-co is "only" 98 people I believe. Up to the others in #desc-announce to join #desc-co to be kept up to date..... comments?

We did discuss this on [Slack on this thread](https://lsstc.slack.com/archives/C2M6H2LAX/p1632355729042700).  #desc-co may not be broad enough, and #desc-announce might actually be too broad.  We thought about reposting certain RFCs to other channels when appropriate to help keep people informed.  Admittedly that is a manual process, perhaps we can add that to the checklist.  Offline, Eric C also noted that we should really make sure the PS are properly included in this and we need to do that too, starting with how this is ultimately announced and advertised.

**Comment by johannct** [comment]
Sorry I was not clear : the start of the RFC should be advertised in the largest circle, mentioning there that for now traffic will be directed to #desc-co, and that people who feel or should feel concerned (CI PS conveners) should join CO.

**Comment by heather999** [comment]
Joanne suggested we make sure to express the scope and some examples in the README.

**Comment by heather999** [comment]
**I'm going to label this "adopted" tomorrow morning, Friday, Oct 1st and start work on the items listed below.  If you have final comments or suggestions, please offer them now.**

Here's a preliminary decision: 
* PR coming with updates to the README, including scope, examples and an outline of this checklist above.
* A draft announcement will be written and circulated for comment
* Then an announcement will be made.

The above steps will be handled via a new "project" and associated GH issues to track progress - just to exercise the system.
